version: "3.8"
services:
  node:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: node_clinica
    working_dir: /home/node/app
    command: yarn dev
    volumes:
      - ./:/home/node/app
    ports:
      - ${APP_PORT}:3000
    env_file:
      .env
